name       : python-wsproto
version    : 1.1.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/w/wsproto/wsproto-1.1.0.tar.gz : a2e56bfd5c7cd83c1369d83b5feccd6d37798b74872866e62616e0ecf111bda8
homepage   : https://github.com/python-hyper/wsproto/
license    : MIT
component  : programming.python
summary    : Sans-IO WebSocket protocol implementation
description: |
    This is a pure-Python implementation of a WebSocket protocol stack. It’s written from the ground up to be embeddable in whatever program you choose to use, ensuring that you can communicate via WebSockets, as defined in RFC6455, regardless of your programming paradigm.
builddeps  :
    - python-h11    # check
    - python-pytest # check
rundeps    :
    - python-h11
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
